Allow instructor to skip question
uncc-hice/edukona_backend pull request #42
Opened 2024-10-16 17:48 UTC by AustinfHunter

**Summary:**
Added functionality that allows the instructor to skip a question. When a question is skipped, all students associated with the session will have their responses updated with the question_skipped field set to true in order to maintain data integrity and allow for calculations based on responses to handle skipped questions.

**Changes:**
1. Added the skip_question_db method to the InstructorConsumer class. This handles updating data related the question to include a skipped status, locks the question, and creates skipped responses for all students associated with the current quiz session.
2. Added the skip_question method to the InstructorConsumer class. This sends a response to the instructor including the number of student responses updated.

**Examples:**
Instructor skipping question
![successful_lock](https://github.com/user-attachments/assets/612dd060-e445-404a-9103-4a7c92573e28)

Student response fails when question has been skipped
![student_fails_afer_lock](https://github.com/user-attachments/assets/7c5567df-c67d-4747-807b-7c677fc52a08)

2024-10-18 22:22 UTC, amhajja approved these changes
Very nice, Austin; thank you for making the requested change(s)!

2024-10-19 03:32 UTC, amhajja requested changes
@aaladaruncc, left a minor comment/request.

2024-10-19 03:32 UTC, amhajja commented on api/consumers.py
> +        await self.send_next_question()
@aaladaruncc, could you please include a Postman screenshot showing this?

2024-10-19 04:50 UTC, aaladaruncc commented
> @aaladaruncc, left a minor comment/request.

Here is the screenshot, I have also attached to the review:


<img width="752" alt="image" src="https://github.com/user-attachments/assets/f2a53446-03aa-495b-a019-92a488150b29">

2024-10-19 13:19 UTC, amhajja approved these changes
Looks great, thank you @AustinfHunter an @aaladaruncc!

2024-10-19 13:19 UTC, merged