Added grades to the quiz end
uncc-hice/edukona_backend pull request #46
Opened 2024-10-19 01:01 UTC by aaladaruncc

2024-10-19 03:29 UTC, amhajja requested changes
Left a comment.

2024-10-19 03:29 UTC, amhajja commented on api/consumers.py
> +            grade_buckets[grade].append(student.username)
Here, you're assuming we're having 5 questions; you should probably do:

`grade_buckets[str(round(percentage, 2))].append(student.username)`

Another approach would be to get the number of questions, then create buckets for every possible grade.

2024-10-19 04:41 UTC, aaladaruncc commented
> Left a comment.

Resolved the issue, I updated the way the grade buckets are calculated.

2024-10-19 13:58 UTC, amhajja requested changes
Found another issue.

2024-10-19 13:58 UTC, amhajja commented on api/consumers.py
> +        return grade_buckets
There might be an issue with this logic now that I'm taking a second look; `total_responses = responses.count()` may not be the number of questions in the quiz; if a student does not submit an answer, there won't be a record in that table.

Total responses should be retrieved from `api_quiz_session_question`, and it should ignore skipped questions, when you get `correct_responses` you should also ignore the questions that were skipped (using `skipped` attribute in `api_quiz_session_question` and not `skipped_question` in `api_user_response`)

Also, how have you tested this? Is there an easy way for the PR reviewer to test this?

2024-10-21 04:12 UTC, amhajja requested changes
I like that you added new consumer tests; however, are you sure the test is running in our Django test workflow (I don't believe it is)?

Also, please see the comments I left, and please resolve flake8 errors.

2024-10-21 18:17 UTC, aaladaruncc commented
> I like that you added new consumer tests; however, are you sure the test is running in our Django test workflow (I don't believe it is)?
> 
> Also, please see the comments I left, and please resolve flake8 errors.

The tests for consumers aren't part of the django tests flow right now. But you can pull the code and run the following command to run the test: `pytest ./api/tests/consumer_tests.py`. In a future ticket we can integrate the consumer tests in the github workflow.

2024-10-22 14:45 UTC, amhajja approved these changes
This looks great; we should talk about the test that you added during our meeting on Wednesday/Friday.

2024-10-22 14:45 UTC, merged