feat: add token verification endpoint and corresponding tests
uncc-hice/edukona_backend pull request #78
Opened 2024-11-11 20:56 UTC by BruhLemma-Yadecha

This pull request introduces a new feature for token verification and includes corresponding tests. The key changes involve adding a new view for token verification, updating the URL routing, and adding tests to ensure the functionality works as expected.

### New Feature: Token Verification

* **Token Verification View**: Added `TokenVerificationView` class to handle GET requests for verifying tokens.
* **URL Routing**: Added a new URL pattern for token verification in `hice_backend/urls.py`.

### Testing

* **New Test Class**: Added `TokenVerificationTest` class to test the token verification feature, including tests for both successful and failed token verifications.

2024-11-11 21:13 UTC, aaladaruncc approved these changes
Looks great!

2024-11-12 07:04 UTC, amhajja requested changes

2024-11-12 07:04 UTC, amhajja commented on api/views/user_views.py
> +        return JsonResponse({"message": "Token is valid"}, status=status.HTTP_200_OK)
Let's simplify the logic to something like this:
```
class TokenVerificationView(APIView):
    permission_classes = [IsAuthenticated]

    def get(self, request):
        return Response({"message": "Token is valid"}, status=status.HTTP_200_OK)
```

We should also add a `throttle_classes` to this endpoint.

2024-11-13 00:52 UTC, amhajja requested changes
One last request.

2024-11-13 00:52 UTC, amhajja commented on hice_backend/urls.py
> +        "token/verify/<str:token>/",
Token should not be sent/accepted in URL; it'll be in the authorization header.

2024-11-13 05:29 UTC, amhajja approved these changes
Looks good; thanks for making the requested changes!

2024-11-13 05:31 UTC, merged